tasks:
        2008R2-2012R2-runtest:
                jobmd: 'non_gating'
                whql_cmd: '2008R2_2012R2'
        WIN732-WIN764-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'WIN732_WIN764'
        WIN832-WIN864-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'WIN832_WIN864'
        BLUE32-BLUE64-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'BLUE32_BLUE64'
        WIN201264-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'WIN201264'
        W10D32-W10D64-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'W10D32_W10D64'
        WIN2016-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'WIN2016'
        WIN2019-runtest:
                jobmd: 'non_gating'
                whql_cmd: 'WIN2019'

jobmd_list:
        non_gating:
                email_recipients: 'xiagao@redhat.com, lijin@redhat.com, wyu@redhat.com, phou@redhat.com'
                job_owner: 'xiagao'

wqhl_cmd_list:
        package: 'libvirt'
        install_params: '--verbose --downgrade --install-virtqemu ${{LATEST_FAST_VIRT}}'
        2008R2_2012R2:
                hostname: 'dell-per730-47.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 08 -a R2 -c 192.168.0.5'
                cmd_base2: 'python3 XMLParsing.py -p 12 -a R2 -c 192.168.0.5'
        WIN732_WIN764:
                hostname: 'dell-per730-48.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 07 -a 32 -c 192.168.0.5'
                cmd_base2: 'python3 XMLParsing.py -p 07 -a 64 -c 192.168.0.5'
        WIN832_WIN864:
                hostname: 'dell-per440-01.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 08 -a 32 -c 192.168.0.5'
                cmd_base2: 'python3 XMLParsing.py -p 08 -a 64 -c 192.168.0.5'
        BLUE32_BLUE64:
                hostname: 'dell-per440-02.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 81 -a 32 -c 192.168.0.5'
                cmd_base2: 'python3 XMLParsing.py -p 81 -a 64 -c 192.168.0.5'
        WIN201264:
                hostname: 'dell-per440-03.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 12 -a 64 -c 192.168.0.5'
                cmd_base2: 'None'
        W10D32_W10D64:
                hostname: 'dell-per440-04.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 10 -a 32 -c 192.168.0.10'
                cmd_base2: 'python3 XMLParsing.py -p 10 -a 64 -c 192.168.0.10'
        WIN2016:
                hostname: 'dell-per440-05.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 16 -a 64 -c 192.168.0.3'
                cmd_base2: 'None'
        WIN2019:
                hostname: 'dell-per440-06.lab.eng.pek2.redhat.com'
                cmd_base1: 'python3 XMLParsing.py -p 19 -a 64 -c 192.168.2.148'
                cmd_base2: 'None'
