builds:
        virtio-win:
                target_stream:
                        el8:
                                tasks:
                                        win2012-win2016-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win2012_win2016_el8'
                                        blue-win2019-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'blue_win2019_el8'
                                        win10-win2012r2-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win10_win2012r2_el8'
                        el7:
                                tasks:
                                        win2012-win2016-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win2012_win2016_el7'
                                        blue-win2019-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'blue_win2019_el7'
                                        win10-win2012r2-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win10_win2012r2_el7'
                        el9:
                                tasks:
                                        win2012-win2016-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win2012_win2016_el9'
                                        blue-win2019-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'blue_win2019_el9'
                                        win10-win2012r2-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win10_win2012r2_el9'
        virtio-win-prewhql:
                target_stream:
                        el8:
                                tasks:
                                        win2012-win2016-win2022-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win2012_win2016_win2022_el8'
                                        blue-win2019-win11-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'blue_win2019_win11_el8'
                                        win10-win2012r2-runtest:
                                                jobmd: 'non_gating'
                                                kar_cmd: 'win10_win2012r2_el8'
jobmd_list:
        non_gating:
                email_recipients: 'xiagao@redhat.com, lijin@redhat.com, phou@redhat.com, menli@redhat.com, demeng@redhat.com, leidwang@redhat.com'
                job_owner: 'lijin'
                is_gating: 'false'
        gating:
                email_recipients: 'xiagao@redhat.com, lijin@redhat.com, phou@redhat.com, menli@redhat.com, demeng@redhat.com, leidwang@redhat.com'
                job_owner: 'lijin'
                is_gating: 'true'
kar_cmd_list:
        win2012_win2016_el8:
                cmd: 'python3 ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win2012..r1,Win2016 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng --machines=q35'
                install_params: '--verbose --install-virtqemu ${{LATEST_FAST_VIRT}}'
                hostname: 'dell-per440-01.lab.eng.pek2.redhat.com'
        win2012_win2016_win2022_el8:
                cmd: 'python3 ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win2012..r1,Win2016,Win2022 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng --machines=q35'
                install_params: '--verbose --install-virtqemu ${{LATEST_FAST_VIRT}}'
                hostname: 'dell-per440-01.lab.eng.pek2.redhat.com'
        win2012_win2016_el7:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win2012..r1,Win2016 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm-rhev@rhevh-rhel-${{OS_VERSION}}-candidate'
                hostname: 'dell-per440-01.lab.eng.pek2.redhat.com'
        win2012_win2016_el9:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win2012..r1,Win2016 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm@rhel-${{OS_VERSION}}-beta-candidate'
        blue_win2019_el8:
                cmd: 'python3 ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win8..1,Win2019 --clone=yes --rng_type=no_virtio_rng,virtio_rng --machines=q35'
                install_params: '--verbose --install-virtqemu ${{LATEST_FAST_VIRT}}'
                hostname: 'dell-per440-02.lab.eng.pek2.redhat.com'
        blue_win2019_win11_el8:
                cmd: 'python3 ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win8..1,Win2019,Win11.x86_64 --clone=yes --rng_type=no_virtio_rng,virtio_rng --machines=q35'
                install_params: '--verbose --install-virtqemu ${{LATEST_FAST_VIRT}}'
                hostname: 'dell-per440-02.lab.eng.pek2.redhat.com'
        blue_win2019_el7:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win8..1,Win2019 --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm-rhev@rhevh-rhel-${{OS_VERSION}}-candidate'
                hostname: 'dell-per440-02.lab.eng.pek2.redhat.com'
        blue_win2019_el9:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win8..1,Win2019 --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm@rhel-${{OS_VERSION}}-beta-candidate'
        win10_win2012r2_el8:
                cmd: 'python3 ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win10,Win2012..r2 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng --machines=q35'
                install_params: '--verbose --install-virtqemu ${{LATEST_FAST_VIRT}}'
                hostname: 'dell-per440-03.lab.eng.pek2.redhat.com'
        win10_win2012r2_el7:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win10,Win2012..r2 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm-rhev@rhevh-rhel-${{OS_VERSION}}-candidate'
                hostname: 'dell-per440-03.lab.eng.pek2.redhat.com'
        win10_win2012r2_el9:
                cmd: 'python ConfigTest.py --category=${{LOOP_NAME}} --guestname=Win10,Win2012..r2 --driveformat=virtio_blk --clone=yes --rng_type=no_virtio_rng,virtio_rng'
                install_params: 'qemu-kvm@rhel-${{OS_VERSION}}-beta-candidate'
